### ISSUE TITLE
download as an image feature is not working

### ISSUE THREAD

**Issue by axs165032** [keplergl/kepler.gl#150]
I tried downloading the visualization, I was working on and the export as image feature did not work

**Comment by heshan0131** [comment]
Fix is coming

**Comment by heshan0131** [comment]
This should be resolved. Closing it for now

**Comment by chintanp** [comment]
The export to image feature is still not working for me. The animation circle keeps on rotating, and nothing happens further.

**Comment by heshan0131** [comment]
Hi @clintanp, which browser are you using? Can you open your browser console while you export and take a screenshot of the errors if there is any?

**Comment by chintanp** [comment]
Please see attached. I am using Firefox 61.0 (64-bit) on Windows 10. 

![kepler gl_error_export](https://user-images.githubusercontent.com/752869/42484312-2ce7644a-83a7-11e8-986a-bcadb8acd87a.PNG)

**Comment by heshan0131** [comment]
@chintanp 
Are you using the kepler.gl/#/demo app or running kepler.gl in your local environment
Seems like firefox throws an error when requesting CORS stylesheets.

I can't seem to repoduce this error in my firefox at the moment. (I m on mac). 
You can try to use chrome on windows as a workaround

**Comment by chintanp** [comment]
I am using the http://kepler.gl/#/demo app and it doesn't work in Chrome (67.0) on my machine too.  Error in chrome as below: 

![kepler gl_error_export_chrome](https://user-images.githubusercontent.com/752869/42541385-f91d1a96-8456-11e8-8a69-6a5c55c1311e.PNG)

**Comment by chrisirhc** [comment]
@chintanp are you still seeing this issue? If so, could you clear your cache and try again?
I'm unable to reproduce it and I do see the required `Access-Control-Allow-Origin` header sent by the server:
![image](https://user-images.githubusercontent.com/132584/42545294-e5dd94a0-846b-11e8-89ca-2833605aa21e.png)

**Comment by chintanp** [comment]
I tried again after clearing cache etc. but I am still getting the same error and it doesn't work for me. If it works for everyone else, then maybe something wrong with my setup.

**Comment by heshan0131** [comment]
@chintanp if you can open your network tab, find the refresh.css request, and send me a screenshot of the Header, that would be really helpful. I just helped someone debug this issue using chrome. As soon as I check the `disable cache` box, the image showed up.

<img width="871" alt="screen shot 2018-07-12 at 1 20 37 pm" src="https://user-images.githubusercontent.com/3605556/42658465-45e5bb2e-85da-11e8-9a2d-1f66ea4ef261.png">

**Comment by chintanp** [comment]
@heshan0131 : Thank you for your persistence in helping me. I can confirm that it works for me on Chrome now. I did have to click on "Disable Cache" once, and then it has been working on Chrome since. However, this option doesn't work for Firefox, and we still have a rotating disk when trying to export in Firefox.

**Comment by heshan0131** [comment]
https://github.com/uber/kepler.gl/pull/360
