### ISSUE TITLE
Stagnant response after dataset load in some cases [Bug]

### ISSUE THREAD

**Issue by apoorvm91** [keplergl/kepler.gl#2395]
**Describe the bug**
After loading the dataset, the loading status bar states "100%" but the image does not render. This is similar to the issue I have reported previously #1963 and in fact, some of the exact same json files are producing this error. Although I observe that not all of the json files lead to this issue. I tried both loading from the URL as well as loading the json files directly.

**To Reproduce**
Unable to upload the json file as it is too large but the console error is shown below in the screenshot.

**Expected behavior**
Expected to load the analysis maps I had previously worked on and saved.

**Screenshots**
![image](https://github.com/keplergl/kepler.gl/assets/9020327/457fa2c0-2da1-46cc-803c-a42659261b3e)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Microsoft Edge for Business
 - Version 118

**Comment by apoorvm91** [comment]
See if you are able to access this file: https://www.dropbox.com/scl/fi/kk13hw86qmn8wl0jrq3ba/keplergl_2o0224.png?rlkey=2olpw1xx51i4eseh69wfkkbp5&dl=0

**Comment by ibgreen** [comment]
Yes I can, that is a PNG file. Sorry for being so out of the loop, but are you trying to load JSON files or PNG files? Maybe you are just testing if I can access?

**Comment by apoorvm91** [comment]
My apologies. I updated the link. 
https://www.dropbox.com/s/oe6q20akilcc38a/keplergl_8dxo22b.json?dl=0

**Comment by ibgreen** [comment]
@igorDykhta can you take a look?

**Comment by apoorvm91** [comment]
Following up on this to see if I can provide any additional information to help resolving the bug.

**Comment by apoorvm91** [comment]
@igorDykhta : I am not sure of the version as I am trying to open it on the web interface. 
Are you able to open this link? https://[kepler.gl](https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/611gndnmbxlu7cu/keplergl_2o0224.json)/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/611gndnmbxlu7cu/keplergl_2o0224.json

**Comment by lixun910** [comment]
@igorDykhta This should be fixed in https://github.com/keplergl/kepler.gl/pull/2381 Can you help to review this PR and merge it? Thanks!

**Comment by apoorvm91** [comment]
@lixun910 @igorDykhta I still see the same issue on my end. Was the merge executed?
